### ISSUE TITLE
Missing null check for MsSqlEventStore CreateEventStoreNotifier

### ISSUE THREAD

**Issue by emragins** [damianh/Cedar.EventStore#26]
If you create a new store with 

`var store = MsSqlEventStore(connectionString, null);`

then later try to add a subscription

`store.SubscribeToAll(null, se => { DoStuff(se); });`

It fails with a generic 

`System.NullReferenceException: Object reference not set to an instance of an object.`

With the below origin:

```
public MsSqlEventStore(
    string connectionString,
    CreateEventStoreNotifier createEventStoreNotifier,
    string schema = "dbo",
    string logName = "MsSqlEventStore")
    :base(logName)
{
    Ensure.That(connectionString, nameof(connectionString)).IsNotNullOrWhiteSpace();

    _createConnection = () => new SqlConnection(connectionString);
    _eventStoreNotifier = new AsyncLazy<IEventStoreNotifier>(
        async () => await createEventStoreNotifier(this).NotOnCapturedContext()); <--- HERE
    _scripts = new Scripts(schema);
}
```

It would be nice to have a better error message along the lines of "Cannot create notifier because supplied createEventStoreNotifier was null"... 

Stylistically I'm not sure how you want to handle this.

Maybe something like 

```
// untested code
_eventStoreNotifier = new AsyncLazy<IEventStoreNotifier>(
    async () => 
        {
        if(createEventStoreNotifier == null)
            throw new ArgumentNullException("Cannot create notifier because supplied createEventStoreNotifier was null");
        return await createEventStoreNotifier(this).NotOnCapturedContext()); 
    });

```

**Comment by damianh** [comment]
Fixed via https://github.com/damianh/Cedar.EventStore/commit/2495f6d122b0ce366f116c5f4b3ec294ea131780 (I put the wrong issue number in the commit).

Thanks for reporting!
