### ISSUE TITLE
documentation :-)

### ISSUE THREAD

**Issue by mickdelaney** [damianh/Cedar.EventStore#4]
hi,

just wondering if i'm looking for info on architectural decisions/approaches, should i look at the neventstore docs as inspiration ??? 

i'm looking for a simple ES solution on top of postgres + geteventstore, so this seems to be perfect.

**Comment by jruizaranguren** [comment]
It would be great to have at least a brief rationale, or plans about this project. After reading [this proposal](http://squirrel.pl/blog/2015/09/14/achieving-consistency-in-cqrs-with-linear-event-store/) It is clear that event store infrastructure over RDBMS can be much lighweight than [neventstore](https://github.com/NEventStore).

**Comment by damianh** [comment]
Hey guys, thank you for your interest in this. I am busy at working on it at the moment.. I want to get it to a reasonable _working_ state and that the things I want to see working are actually achievable. I don't want to set expectations wrong or too early. Then comes the docs, blogs posts etc.

I will create an issues to track to an initial 0.1 release.

**Comment by mickdelaney** [comment]
thanks damian, will close this for now until the first official release.
