### ISSUE TITLE
buckets for natural stream partitions

### ISSUE THREAD

**Issue by jruizaranguren** [damianh/Cedar.EventStore#5]
I'm aware it is pretty soon to add issues here, but, I'll ask anyway :smile: 

Do you plan to add a bucket column in order to make it easy to partition streams in RDBMS (as in NEventStore)? Or do you plan to avoid it making in order to be more GES compatible?

**Comment by damianh** [comment]
Hi @jruizaranguren yes a bit soon (and hence the slow reply).

At this point my answer is no... mostly because RDMBs are fairly good at running multiple databases and it's simple to have multiple eventstore instance. The NEventStore approach was built like that because of the goal of supporting no-sql stores which is not a ~~restriction~~ goal of mine.

I think a future version of GES may support multi-tenancy. I know they have been thinking of that.

From your perspective, what benefits would a bucket concept bring you?

**Comment by jruizaranguren** [comment]
It has made it easier for me in the past to deal with operational stuff. A bucket column can be used for multi-tenancy but also to separate modules or bounded contexts. The decision of creating isolated databases can be done later in a project just if needed.

**Comment by damianh** [comment]
Reasonable. MS calls this "[Shared Database, Shared Schema](https://msdn.microsoft.com/en-us/library/aa479086.aspx)". 

I'm thinking of supporting multiple event stores in one database via "[Shared Database, Separate Schemas]". I think this may strike the right balance.

**Comment by jruizaranguren** [comment]
Great. That would fit my typical scenarios neatly. In any case, the important thing is if there exists an external parameter in the `IEventStore` interface (or convention over `streamId` naming) that can be used to deal with *schemas/partitions/databases/columns* as a database implementation detail. 

Some RDBMS may not have exactly the same `schema` concept (`SQLite`? `mySQL`?), and despite not beeing your goal, it seems a quite cheap way to have the interface open to a wider range of types of DBs.

**Comment by danbarua** [comment]
Postgres has support for schemas: https://github.com/danbarua/Cedar.EventStore/commit/9f271e6cbb1400d5da9bb932abd52f74b89d0ab6

**Comment by damianh** [comment]
Instead it on the interface itself (and thus forcing all implementations to support it) I prefer @danbarua's solution of making it a ctor parameter of each event store implementation that supports the concept:

```
var bucketFoo = new MsSqlEventStore(... , schema: "foo");
var buckerBar = new MsSqlEventStore(... , schema: "foo");
```

The only caveat I can think of is that each schema will need initialization.

**Comment by jruizaranguren** [comment]
I also think that solution is preferable. 
This might depend on tastes, but I also would prefer a convention based solution that is inferred from the key number (à la `S3`). 

So `streamID = "partitionKey/streamId"` is decomposed to a streamId and a schema/partition/database/columnFamily.

That would leave each store to choose the implementation, if any. You may choose in the constructor:

```
var bucketFoo = new MsSqlEventStore(... , initializeSchemaIfNotExists: true);
```

**Comment by damianh** [comment]
The schema support is on `master`

@jruizaranguren I'm not going to implement / partition keys in stream Id's at this time. I'd have to propagate that `StreamEventsPage` and other places. I _suspect_ there is hidden complexity. Would a wrapper `IEventStore` implementation that does this work be possible?

**Comment by jruizaranguren** [comment]
I do not understand why having a `streamId` naming convention would affect to `StreamEventsPage`. It would probably affect to `StreamIdInfo` and internal implementations for each store: `ReadStreamInternal`, `AppendToStreamInternal` functions, But it would still be a string for any other method.
Thanks for adding the schema support, I guess it will cover most of use cases. Further generalization of partitions/etc. can be done in later stages of the project if succeeds as it deserves, and if it is required by hordes of people. :smiley:

**Comment by damianh** [comment]
> Further generalization of partitions/etc. can be done in later stages of the project if succeeds as it deserves, and if it is required by hordes of people. 

Haha yes :) This schema approach doesn't preclude further generalization.

Thanks for your input :)
